---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

To me, efficiency means accomplishing a goal with the smallest amount of resources possible. As an Industrial Engineering major, it's a term I'm very familiar with. But in terms of statistical computing and data science, this definition can be interpreted as using the least amount of code (which often involves using robust, modern functions) in order to obtain a desired output. Using the least amount of code is important because it makes your code more easily reproducible and understandable by readers (which might be yourself in the future) as well as run faster. It also makes your code easier to change later on.

I encountered efficiency in every single code block in this course. It seemed particularly prevalent in data wrangling: one a-ha moment I had was when I realized mutate executed mutations internal to the function in sequential order. Initially I wasn't sure in what order the mutations would be executed so I called multiple mutate functions just to be sure, which was inefficient. But by the end of the course, I was using mutate highly efficiently by mutating individual columns multiple times within the same mutate function (see dvs-3-3 where I mutated the 'trip' variable twice). Another a-ha moment I had was realizing you could put across() in a dplyr function alongside other statements within the same function (see PE-1-across). A final a-ha moment I had was coming from python and learning about how you can wrangle a data frame and then pipe it directly into ggplot, which blew my mind in terms of the ease and efficiency (see PE-4-2).
